[workspace]
members = ["rv32jit", "rv32assembler"]
resolver = "2"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

# [patch.crates-io]
# rv32assembler = { path = "./rv32assembler" }
