[package]
name = "rv32assembler"
version = "0.1.0"
authors = ["Tommy van der Vorst <tommy@pixelspark.nl>"]
edition = "2021"

[dependencies]
num = "^0.4.0"

[dev-dependencies]
#rvemu = "0.0.11"
rvemu = { git = "https://github.com/pixelspark/rvemu.git", branch = "feature/expose-rom" }